routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('/products', 'ProductController');
/*
Route::get('/products', 'ProductController@index');
Route::get('/products/create', 'ProductController@create');
Route::post('/products', 'ProductController@store');
*/

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::all();
        return view('products.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('products.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $product = new Product;
        $product->name = $request->name;
        $product->price = $request->price;
        $product->quantity = $request->quantity;
        $product->company_name = $request->company_name;
        $product->isAvailable = $request->isAvailable == "on" ? true : false;
        
        $product->save();
        return redirect('products');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = Product::find($id);
        return view('products.show', compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::find($id);
        return view('products.edit', compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {
        $product = Product::find($id);
        $product->name = $request->name;
        $product->price = $request->price;
        $product->quantity = $request->quantity;
        $product->company_name = $request->company_name;
        $product->isAvailable = $request->isAvailable;
        
        $product->save();
        return redirect('products');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Product::find($id)->delete();
        return redirect('/products');
    }
}

resources/views/layout/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>@yield('title')</title>
    <link rel="stylesheet" href="/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/products/">Scripted</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/products">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/products/create">Create</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container-fluid">
        @yield('content')
    </div>

    <script src="/js/bootstrap.min.js"></script>
</body>
</html>

resources/views/products/create.blade.php
@extends('layout.layout')
@section('title', 'Create Product')
@section('content')
    <form method="post" action="/products">
    @csrf
    
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" name="name" class="form-control">
        </div>
        <div class="form-group">
            <label for="price">Price</label>
            <input type="text" name="price" class="form-control">
        </div>
        <div class="form-group">
            <label for="quantity">Quantity</label>
            <input type="text" name="quantity" class="form-control">
        </div>
        <div class="form-group">
            <label for="company_name">Company Name</label>
            <input type="text" name="company_name" class="form-control">
        </div>
        <div class="custom-control custom-checkbox">
            <input type="checkbox" class="custom-control-input" id="customCheck1" name="isAvailable">
            <label class="custom-control-label" for="customCheck1">isAvailable</label>
        </div>
        <button type="submit" class="btn btn-outline-primary btn-bg">Save</button>
    </form>
@endsection

resources/views/products/edit.blade.php
@extends('layout.layout')
@section('title', 'Edit')
@section('content')

<form method="post" action="/products/{{ $product->id }}">
@csrf
@method('PUT')
<div class="form-group">
            <label for="name">Name</label>
            <input type="text" name="name" class="form-control" value="{{$product->name}}">
        </div>
        <div class="form-group">
            <label for="price">Price</label>
            <input type="text" name="price" class="form-control" value="{{$product->price}}">
        </div>
        <div class="form-group">
            <label for="quantity">Quantity</label>
            <input type="text" name="quantity" class="form-control" value="{{$product->quantity}}">
        </div>
        <div class="form-group">
            <label for="company_name">Company Name</label>
            <input type="text" name="company_name" class="form-control" value="{{$product->company_name}}">
        </div>
        <div class="form-check">
            <input type="checkbox" id="isAvailable" name="isAvailable" value="{{$product->isAvailable}}">
            <label for="isAvailable"> Available</label>
        </div>
        <button type="submit" class="btn btn-outline-primary btn-bg">Update</button>
</form>

@endsection

resources/views/products/index.blade.php
@extends('layout.layout')

@section('title', 'Product')

@section('content')

<div class="container">
  <h3 class="display-4">Product List</h3>
  <table class="table table-condensed">
    <thead>
      <tr>
        <td>Name</td>
        <td>Price</td>
        <td>Quantity</td>
        <td>Company Name</td>
        <td>Status</td>
        <td>Action</td>
      </tr>
    </thead>
    <tbody>
      @foreach($products as $product)
        <tr>
          <td> <a href="{{route('products.show', $product->id)}}"> {{$product->name}} </a></td>
          <td> {{$product->price}} </td>
          <td> {{$product->quantity}} </td>
          <td> {{$product->company_name}} </td>
          <td> 
            @if($product->isAvailable == true)
              Available
            @else
              Not Available
            @endif
           </td>
           <td>
            <form action="{{route('products.destroy',$product->id)}}" method="post">
              @csrf
              @method('DELETE')
              <button type="submit" class="btn btn-outline-danger">Delete</button>
            </form>
           </td>
        </tr>
      @endforeach
    </tbody>
  </table>


</div>

@endsection

resources/views/products/show.blade.php
@extends('layout.layout')
@section('title', 'show')
@section('content')

<div class="container text-center">
    <div class="card">
        <div class="card-heading bg-primary"><h3>Product Details</h3></div>
        <div class="card-body bg-light">
            <p>Product Name: {{$product->name}}</p>
            <p>Product Price: {{$product->price}}</p>
            <p>Product Quantity: {{$product->quantity}}</p>
            <p>Product Company: {{$product->company_name}}</p>
            <p>Product Availability: <span class="bg-warning">{{$product->isAvailable == true? 'Available' : 'Not Available' }}</span></p>
        </div>
    </div>
</div>

@endsection